# Generated by Django 4.0.2 on 2023-09-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnServe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_organization', models.CharField(max_length=200)),
                ('name_of_person', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('contact_number', models.IntegerField(max_length=20000)),
                ('num_of_pos_available', models.IntegerField(default=100)),
                ('email', models.EmailField(max_length=200)),
                ('qualification', models.CharField(max_length=200)),
                ('area_of_interest', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='TeachingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_person', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('contact_number', models.IntegerField(max_length=20000)),
                ('email', models.EmailField(max_length=200)),
                ('qualification', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VolenteerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('contact_number', models.IntegerField(max_length=20000)),
                ('email', models.EmailField(max_length=200)),
                ('area_of_interest', models.CharField(max_length=2000)),
            ],
        ),
    ]
