# Generated by Django 4.0.2 on 2023-09-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnServe', '0002_scoutingregistration_teachingregistration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingregistration',
            name='contact_number',
            field=models.IntegerField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='teachingregistration',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teachingregistration',
            name='name_of_person',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teachingregistration',
            name='qualification',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teachingregistration',
            name='region',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
