# Generated by Django 4.0.2 on 2023-09-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnServe', '0003_alter_teachingregistration_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingregistration',
            name='contact_number',
            field=models.IntegerField(null=True),
        ),
    ]
