# Generated by Django 4.0.2 on 2023-09-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnServe', '0004_alter_teachingregistration_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingregistration',
            name='subject_taught',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
