# Generated by Django 4.0.2 on 2023-09-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnServe', '0005_teachingregistration_subject_taught'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingregistration',
            name='subject_taught',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
