# Generated by Django 4.0.2 on 2023-09-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnServe', '0006_alter_teachingregistration_subject_taught'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('contact_number', models.IntegerField(max_length=200)),
                ('region', models.CharField(max_length=200, null=True)),
                ('subject', models.CharField(choices=[('MATH', 'math'), ('SCIENCE', 'science'), ('ENGLISH', 'english'), ('SOCIAL_STUDIES', 'social_science'), ('HINDI', 'hindi')], default='math', max_length=200)),
            ],
        ),
    ]
