# Generated by Django 4.0.2 on 2023-09-20 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearnServe', '0008_teachingregistration_dates_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScoutingRegistration',
        ),
    ]
