# Generated by Django 4.0.2 on 2023-09-20 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LearnServe', '0009_delete_scoutingregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='name',
        ),
        migrations.RemoveField(
            model_name='teachingregistration',
            name='name_of_person',
        ),
        migrations.RemoveField(
            model_name='volenteerregistration',
            name='name',
        ),
        migrations.AddField(
            model_name='education',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teachingregistration',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='volenteerregistration',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='choice',
            name='cool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LearnServe.testmodel'),
        ),
        migrations.AlterField(
            model_name='education',
            name='contact_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='volenteerregistration',
            name='contact_number',
            field=models.IntegerField(),
        ),
    ]
